import { Button} from "std-widgets.slint";
import {Palette} from "palette.slint";

component MetronomeButton inherits Rectangle {
    
    height: 60px;
    //later polygons or icons instead text
    in-out property <string> text;
    in-out property <bool> disabled: false;
    min-width: 40px;  
    

    callback clicked();

    border-radius: 20px;

    background: disabled ? Palette.accent-disabled : Palette.accent;
    Text {
        text: text;
        color: disabled ? Palette.background-disabled : Palette.background;
    }

    TouchArea {
        clicked => {
            root.clicked();
        }
    }
}

component PlayStopButton inherits MetronomeButton {
    out property <bool> playing: false;
    clicked => {
        playing = !playing;
    }

    states [
        playing when playing: {
            text: "s";
        }
        stopped when !playing: {
            text: "p";
        }
    ]
}
component ResetButton inherits MetronomeButton {
    text: "r";
}
component RepeatButton inherits MetronomeButton {
    out property <bool> repeated: false;

    clicked => {
        repeated = !repeated;
    }
    states [
        repeated when repeated: {
            text:  "r";
        }
        once when !repeated: {
            text: "o";
        }
    ]
}


export component ControlPanel inherits Rectangle {
    out property <bool> playing: play-stop.playing;
    out property <bool> repeated: repeat.repeated;

    callback play-stop();
    callback reset();
    callback repeat();

    callback enable-play-button();
    callback disable-play-button();

    width: 100%;

    HorizontalLayout {
        width: parent.width;
        padding-left: 30px;
        padding-right: 30px;
        spacing: 15px;
        alignment: stretch;
        reset := ResetButton { 
            horizontal-stretch: 1;
            clicked => { root.reset(); }
        }
        play-stop := PlayStopButton {
            horizontal-stretch: 1;
            clicked => { root.play-stop(); }
        }
        repeat := RepeatButton {
            horizontal-stretch: 1;
            clicked => { root.repeat(); }
        }
    }
}