import { Button} from "std-widgets.slint";
import {Palette} from "palette.slint";
import { ButtonLogic } from "logic.slint";

component MetronomeButton inherits Rectangle {
    
    //later polygons or icons instead text
    in-out property <string> text;
    
    in-out property <bool> disabled: false;

    callback clicked();
    
    height: 60px;
    border-radius: 20px;
    min-width: 40px;  
    
    background: disabled ? Palette.accent-disabled : Palette.accent;

    Text {
        text: parent.text;
        color: disabled ? Palette.background-disabled : Palette.background;
    }

    TouchArea {
        clicked => {
            parent.clicked();
        }
    }
}

component PlayButton inherits MetronomeButton {
    
    clicked => {
        ButtonLogic.play-button-pressed();
        debug("play clicked");
        ButtonLogic.playing = !ButtonLogic.playing;
    }
    text: ButtonLogic.playing ? "p" : "s";
}
component ResetButton inherits MetronomeButton {
    text: "r";
}
component RepeatButton inherits MetronomeButton {
    clicked => {
        ButtonLogic.repeat-button-pressed();
        debug("repead clicked")
    }
    text: ButtonLogic.repeating ? "R" : "r";
}


export component ControlPanel inherits Rectangle {

    callback enable-play-button();
    callback disable-play-button();

    width: 100%;

    HorizontalLayout {
        width: parent.width;
        padding-left: 30px;
        padding-right: 30px;
        spacing: 15px;
        alignment: stretch;
        reset := ResetButton { 
            horizontal-stretch: 1;
        }
        play := PlayButton {
            
            horizontal-stretch: 1;
        }
        repeat := RepeatButton {
            horizontal-stretch: 1;
        }
    }
}