import {Palette} from "palette.slint";
import { Logic } from "logic.slint";
import { HorizontalBox } from "std-widgets.slint";


component BeatCounter inherits Rectangle {
    background: red;
    Text {
        text: Logic.actual-beat;

    }
}

component Signature inherits Rectangle {
    Text {
        text: Logic.numerator + "/" + Logic.denominator;
    }
}
component Tempo {
    Text {
        text: Logic.tempo + " bpm";
    }
}

export component MetronomePanel inherits Rectangle {
    background: Palette.primary;
    
    HorizontalLayout {
        padding: 15px;
        padding-right: 30px;

        BeatCounter {}
        VerticalLayout {
            Signature {}
            Tempo {}
        }
    }
    
}