export global Palette {
    out property <color> background: #222831;
    out property <color> primary: #393E46;
    out property <color> secondary: #948979;
    out property <color> accent: #D9D9D9;

    out property <color> background-disabled: #2C3138;
    out property <color> primary-disabled: #4A4F55;
    out property <color> secondary-disabled: #7A7468;
    out property <color> accent-disabled: #A6A6A6;
}